name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve? Describe the use case, not just the solution you have in mind.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work? Include API examples if possible.
      render: typescript
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Current Workaround
      description: How do you currently work around this limitation?
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Which part of TokenSmith does this affect?
      options:
        - Core (token manager, storage, refresh)
        - React adapter
        - Types / API surface
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Before submitting
      options:
        - label: I have checked the [existing issues](https://github.com/aqib-io/tokensmith/issues) for duplicates.
          required: true
        - label: This cannot be solved with a custom `StorageAdapter` or `refresh.handler`.
          required: false
